### ISSUE TITLE
Getting error while installing keyphrase vectorizer

### ISSUE THREAD

**Issue by ksachdeva11** [TimSchopf/KeyphraseVectorizers#1]
Getting the below error - 
```
!pip install keyphrase-vectorizers 

ERROR: Could not find a version that satisfies the requirement keyphrase-vectorizers (from versions: none)
ERROR: No matching distribution found for keyphrase-vectorizers
```

@TimSchopf

**Comment by ksachdeva11** [comment]
Update - I am seeing this error when installing it on AWS Sagemaker notebook. I am able to install it successfully on my local notebook though.

**Comment by TimSchopf** [comment]
Hey @ksachdeva11 

this error occurs when no matching package is found on PyPI. A common issue when users get this error message is an incompatible Python version. KeyphraseVectorizers needs `Python>=3.7`. Which Python version do you use on AWS SageMaker?

**Comment by ksachdeva11** [comment]
Hey @TimSchopf ... ah okay.. thanks for clearing that. Tried on python3.7 and it works fine.

Closing the issue.
Thank you for quick turnaround!
