### ISSUE TITLE
ValueError: Transformation generated invalid chunkstring

### ISSUE THREAD

**Issue by Kowsalya-Mouttouramane** [TimSchopf/KeyphraseVectorizers#10]
![image](https://user-images.githubusercontent.com/100840630/168606613-bbf3d690-34e2-467f-aa3c-2107e4ea392b.png)
test = ["Les voitures autonomes déplacent la responsabilité de l'assurance vers les constructeurs"]
vectorizer_fr = KeyphraseCountVectorizer(spacy_pipeline='fr_dep_news_trf', pos_pattern='<N.*>+', stop_words ='french')
vectorizer_fr.fit(test)

It generates a valueError : Transformation generated invalid chunkstring:
  <><><><><><><><><><><><>

This works with other languages, the problem is only with the french spacy models (whatever french model).
Can anyone help me solve this error, please ?

**Comment by hboisgibault** [comment]
Hi @Kowsalya-Mouttouramane,
You can check issue #2. In case of the French pipeline, you need to add the transformer pipeline component.
You can use my fork or create a pull request to activate custom components.

**Comment by TimSchopf** [comment]
Closing this as duplicate to issue #2.

**Comment by TimSchopf** [comment]
Closing this as duplicate to issue #2
