### ISSUE TITLE
Can spacy_pipeline utilize spacy's 'en_core_web_trf?

### ISSUE THREAD

**Issue by predoctech** [TimSchopf/KeyphraseVectorizers#11]
Issues:  Current version of Spacy allows the use of packaged transformer pipeline.  KeyphraseVectorizers doesn't seem to accommodate as such in setting up the instance.
Error Message: On calling .fit() function, spacy's ([spacy/tokens/underscore.py in __getattr__(self, name) ) reports the following error:
_AttributeError: [E046] Can't retrieve unregistered extension attribute 'trf_data'. Did you forget to call the `set_extension` method?_
Precondition: already loaded en_core_web_trf, spacy_transformers

Wondering if we can make use of transformer pipeline in KeyphraseVectorizers at all.

**Comment by TimSchopf** [comment]
Hi @predoctech,

currently `en_core_web_trf` is not supported natively in KeyphraseVectorizers. However, you can check issue #2 where the topic was already discussed. In case of the French pipeline, you need to add the transformer pipeline component. You can use the fork of @hboisgibault or create a pull request to activate custom components.

**Comment by TimSchopf** [comment]
I fixed this issue in the new `release v0.0.9` by removing the default exclusion of certain spaCy pipeline components. This slightly slows down the keyphrase extraction process. However it grants higher compatibility to all available spaCy pipelines, including the ones that use transformers.
