### ISSUE TITLE
Can't tag with spaCy in some languages

### ISSUE THREAD

**Issue by mdsutter** [TimSchopf/KeyphraseVectorizers#12]
At least with French, the removal of the morphologizer from the spaCy pipeline means that no tags are able to be added, even when trying to use spaCy's POS tags. I see that there was a recent addition of custom tagger options, but it seems that since spaCy is the default, the removal of the morphologizer is a problem for any language where spaCy uses that instead of a tagger for POS tagging. No tags means no valid chunks and errors when using the package. I tested with a forked version and had no issues once I simply re-added the morphologizer.

**Comment by TimSchopf** [comment]
HI @mdsutter,

the current KeyphraseVectorizers release `v0.0.10` does not exclude any spaCy pipeline components by default anymore. Instead, you can now define which components to exclude in the `space_exclude` parameter. Can you please upgrade your KeyphraseVectorizers version and check if this works for you?

**Comment by TimSchopf** [comment]
I'm closing this issue now and consider it as solved, since I did not receive an answer stating otherwise.
