### ISSUE TITLE
Doesn't seem to work in french

### ISSUE THREAD

**Issue by max2077-python** [TimSchopf/KeyphraseVectorizers#13]
Hi @TimSchopf, 

The package doesn't seem to work in french : it keeps generating the same error "Transformation generated invalid chunkstring:
  <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>". Don't really know where it can come from. As mentioned before, it could come from the POS tags, but not sure about it. It keeps happening in spite of modifying the default spacy_pipeline, pos_pattern and stop_words.

**Comment by TimSchopf** [comment]
Hi @max2077-python,

did you try to use the `fr_dep_news_trf` pipeline using KeyphraseVectorizers `v0.0.10`? Not all spaCy pipelines include a tagger, which probably results in this error. However, there is a French pipeline `fr_dep_news_trf` that uses transformers and that has a tagger for French.

**Comment by max2077-python** [comment]
Well, I had tried it and it kept returning me an empty list. However, I just tried it on another latop and it worked fine, so it was probably an issue with my own computer ! 
Thank you for answering this fast !
