### ISSUE TITLE
POS PATTERN for italian language?

### ISSUE THREAD

**Issue by spolo96** [TimSchopf/KeyphraseVectorizers#14]
First of all @TimSchopf  I would like to thank you so much for this powerful and very easy to use, simple library. I have tested it with some english articles and every keyword returned makes absolutely sense. Yay! 

However, I was trying to follow the guide to use it with other languages, which in my case, I want to see how the library works with the italian language. I got a little lost at the _**pos_pattern**_ parameter, since I've been reading a lot of the spaCy documentation and I don't seem to find the specific pos pattern for the Italian language. I already have the italian spaCy model, which is it_core_news_lg, and a list of italian stopwords, however as I said before I'm a little stuck here because of the pos pattern for the italian language and I wanted to know if you could help me with this simple part😅. 

Thanks in advance!

**Comment by spolo96** [comment]
Hello guys, I already found the solution to own question. In order to use the spacy pipeline with the italian language you have to input the following _**pos_pattern**_: `'<A.*>*<S.*>+'`

For the vectorizer part, the one that I used and obtained good results, I used it like this:

`vectorizer = KeyphraseCountVectorizer(spacy_pipeline='it_core_news_lg', pos_pattern='<A.*>*<S.*>+', stop_words=stop_words)`

I even made a simple function if anyone wants to obtain a list of keywords:

```
# We initialize the model outside the function given the fact that it takes ∼ 5 seconds to load. 
ita_kw_model = KeyBERT(model=SentenceTransformer('paraphrase-multilingual-mpnet-base-v2'))

def keybert_keyphrase_vectorizers_italian(kw_model, article, top_n=20, stop_words=ita_stopwords):
    """Performs Grammatically correct Keyword Extraction using KeyBERT with KeyphraseVectorizers using the spaCy italian pipeline.
    kw_model should be a KeyBERT model with a SentenceTransformer model that includes the italian language. ita_stopwords is
    my custom list of italian stopwords.
    """
    
    article = clean_from_html(article)
    vectorizer = KeyphraseCountVectorizer(spacy_pipeline='it_core_news_lg', pos_pattern='<A.*>*<S.*>+', stop_words=stop_words)
    keywords = kw_model.extract_keywords(docs=article, vectorizer=vectorizer, top_n=top_n)
    
    return keywords
```

And to use the function, just use the following code where *sample_doc* is your italian document.

`keybert_keyphrase_vectorizers_italian(kw_model=ita_kw_model, article=sample_doc)`

**Comment by phuclh** [comment]
@spolo96 How did you figure out that?
