### ISSUE TITLE
Key-phrases extraction based on POS tagging and language models

### ISSUE THREAD

**Issue by Benja1972** [TimSchopf/KeyphraseVectorizers#21]
Hello,
Thank you for nice package for documents vectorization based on extracted key-phrase. 
It looks like few months ago I have created similar approach for key-phrase extraction from single text. 
Beside key-phrase extraction, I have clustered theme in kind of 'topics' and sorted by closeness to centroid or similarity to original document. 

Have a look [](https://github.com/Benja1972/key-topic-bert)

Best
Sergei

**Comment by TimSchopf** [comment]
Hi @Benja1972, 

I believe what you created is something in between a keyphrase extraction and topic modeling approach for single text documents. Very interesting. Thanks for sharing.

**Comment by TimSchopf** [comment]
Hi @Benja1972,

I believe what you created is something in between a keyphrase extraction and topic modeling approach for single text documents. Very interesting. Thanks for sharing.
