### ISSUE TITLE
Keyword similarity values

### ISSUE THREAD

**Issue by arash-hajikhani** [TimSchopf/KeyphraseVectorizers#25]
Would it be possible to retrieve the similarity score between keywords? Once a text is assigned to keywords, would there be a function to retrieve a value on how the keywords are similar to each other?

**Comment by TimSchopf** [comment]
No using KeyphraseVectorizers alone will not return any similarity scores, since this package extracts Keyphrase candidates based on PoS tags and not on similarity scores. Maybe, if you use it together with KeyBERT, you can receive some kind of similarity scores, since the Keyphrases will be ranked by semantic similarity to the source document then.

**Comment by QSTS-Repo** [comment]
Okay thanks for clarifications. I managed to fetch it this way. Can you validate?

```
from keybert import KeyBERT
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Set up the KeyBERT model
model = KeyBERT("distilbert-base-nli-mean-tokens")

# List of keywords
keywords = ['steam boilers', 'boiler']

# Compute similarity scores between all pairs of keywords
similarity_scores = []
for i in range(len(keywords)):
    for j in range(i+1, len(keywords)):
        embeddings = model.extract_embeddings([keywords[i], keywords[j]])
        embeddings = np.concatenate(embeddings)
        similarity_score = cosine_similarity([embeddings[0]], [embeddings[1]], dense_output=False)
        similarity_scores.append(similarity_score[0][0])

# Calculate the average similarity score
average_similarity_score = sum(similarity_scores) / len(similarity_scores)
```

`print(f"The average similarity score between all pairs of keywords is {average_similarity_score:.2f}")`

**Comment by arash-hajikhani** [comment]
Okay thanks for clarifications. I managed to fetch it this way. Can you validate?

from keybert import KeyBERT
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Set up the KeyBERT model
model = KeyBERT("distilbert-base-nli-mean-tokens")

# List of keywords
keywords = ['steam boilers', 'boiler']

# Compute similarity scores between all pairs of keywords
similarity_scores = []
for i in range(len(keywords)):
    for j in range(i+1, len(keywords)):
        embeddings = model.extract_embeddings([keywords[i], keywords[j]])
        embeddings = np.concatenate(embeddings)
        similarity_score = cosine_similarity([embeddings[0]], [embeddings[1]], dense_output=False)
        similarity_scores.append(similarity_score[0][0])

# Calculate the average similarity score
average_similarity_score = sum(similarity_scores) / len(similarity_scores)
print(f"The average similarity score between all pairs of keywords is {average_similarity_score:.2f}")

The average similarity score between all pairs of keywords is 0.86
