### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by dineshdisprz** [TimSchopf/KeyphraseVectorizers#27]
ERROR: Could not find a version that satisfies the requirement keyphrase-vectorizers (from versions: none)
ERROR: No matching distribution found for keyphrase-vectorizers

These are the errors it throws when i try to install the keyphrase-vectorizers module.

can any one help with that ?

**Comment by TimSchopf** [comment]
Do you use `Python >= 3.7` ?

**Comment by dineshdisprz** [comment]
yes ,I do.
