### ISSUE TITLE
OnlineKeyphraseVectorizer

### ISSUE THREAD

**Issue by edloginova** [TimSchopf/KeyphraseVectorizers#29]
Hi!

Thank you for the great project, it does wonders for the interpretability of the topics!
I noticed there doesn't seem to be an Online version, similar to [OnlineCounterVectorizer](https://maartengr.github.io/BERTopic/getting_started/vectorizers/vectorizers.html#onlinecountvectorizer), right? I think it might be a great addition, to allow use in news streams, etc.

**Comment by TimSchopf** [comment]
Added online/incremental updates with the `v0.0.12` release.
