### ISSUE TITLE
It does not exclude stop words in Portuguese

### ISSUE THREAD

**Issue by phuclh** [TimSchopf/KeyphraseVectorizers#31]
I am testing a document in Portuguese, but it doesn't exclude the stop words from the result even I already defined stop_words='portuguese'.

![CleanShot 2023-06-19 at 22 50 08@2x](https://github.com/TimSchopf/KeyphraseVectorizers/assets/6707194/535306b7-af10-4900-84a6-91e0f9d7e0cb)

This is the document that I tested with

[portuguese_doc.txt](https://github.com/TimSchopf/KeyphraseVectorizers/files/11796356/portuguese_doc.txt)

**Comment by TimSchopf** [comment]
Solved with the `v0.0.12` release.
