### ISSUE TITLE
Keyphrases retrieved do not match regex

### ISSUE THREAD

**Issue by hboisgibault** [TimSchopf/KeyphraseVectorizers#8]
Since stopword prefixes and suffixes are removed from the keyphrases, some keyphrases do not match the provided regex.

Let's say my regex only selects group of exactly two nouns. The output could contain one-word keyphrases if some keyphrases contain stop words.

This is by design but it is a problem for our implementation.

**Comment by TimSchopf** [comment]
You could just define `stop_words=None` which doesn't remove any stop words. Would this be an option for you?

**Comment by TimSchopf** [comment]
The v0.0.8 release allows to set `stop_words=None` and should solve this issue.
